# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: FBG-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
    - uses: medyagh/setup-minikube@master
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/checkout@v2
    - name: Build docker images
      run: ./docker-build.sh -db
    - name: Test on minikube
      run: ./misc/test_minikube
    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: e2e-screenshots-${{ github.head_ref }}-${{ github.sha }}
        path: misc/e2e/out/*.png
        retention-days: 5
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn run codegen
    - run: yarn run lint 
    - run: yarn run test
