# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: FBG-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 14.x 
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/checkout@v2
    - run: yarn install --ignore-scripts
    - run: yarn run codegen:genGames
    - run: ./docker-build.sh -bp
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 14.x 
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn run test
