on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - uses: actions/checkout@v2
    - run: cd v2
    - run: yarn install
    - run: cd fbg-web
    - run: yarn run build
    - name: Pushes to another repository
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: out/
        destination-github-username: 'freeboardgames'
        destination-repository-name: 'github-page'
        user-email: robot@FreeBoardGames.org
        commit-message: See ORIGIN_COMMIT from $GITHUB_REF
        target-branch: main
